### ISSUE TITLE
Unify automated installs

### ISSUE THREAD

**Issue by raphaelhoffmann** [HazyResearch/deepdive#302]
We currently have automated installs in the form of 
* vanilla bash scripts
* Dockerfile scripts
* AMIs
* Virtualbox (for impala)

The problem is that it is hard to keep these up-to-date.

I suggest we drop support for Docker/AMIs/Virtualbox. Instead, we'll only have three bash install scripts:
1) install_with_pgxl.sh
2) install_with_pg.sh
3) install_with_greenplum.sh

Running one of these on an Ubuntu Docker container is easy. Running one of these on an Ubuntu VM on ec-2 is easy. Running one of these on an Ubuntu VM in Virtualbox is easy.

We can describe in one short paragraph how to run on any of these hosts.

**Comment by netj** [comment]
This is a great idea.  I totally agree we should move towards this direction to reduce the maintenance burden.  I'll include new instructions in this release if you could share the scripts you have.

**Comment by raphaelhoffmann** [comment]
Thanks – that's great. I just checked some scripts into branch
raphael-script.

You might want to adjust the scripts a bit.

The raw urls which you suggested work fine, eg.

curl -s
https://raw.githubusercontent.com/hazyresearch/deepdive/raphael-script/util/script/dduser_dd.sh
| bash

**Comment by raphaelhoffmann** [comment]
@netj I cleaned up the scripts. The new installer works great.

Get an ec-2 instance with Ubuntu 14.04 and 100GB boot volume. Then run

curl -s https://raw.githubusercontent.com/hazyresearch/deepdive/raphael-script/util/script/entry.sh | bash

Could you link http://deepdive.stanford.edu/install to above script?

**Comment by netj** [comment]
Very nice!  I added a temporary redirect to the website for /install.  It should be updated to point to the master branch upon release, but we can test things with your branch for now.  I think it's better to use raw.github.com instead and add `curl -fsSL`.

**Comment by netj** [comment]
I think ultimately we want to use the same installation scripts for Travis or Shippable tests as well.  Currently, variants of these build/runtime dependency check+installation commands exist all over the place (Makefile, lib/dw_extract.sh, lib/check-depends.sh, .travis.yml, Dockerfile, and now a new set of install scripts!).  Besides, DeepDive doesn't have a clear distinction between source and shippable runtime code.  Instead of distributing obscure binaries over git and running apps against the scala sources and scripts, I seriously think we should build a completely separate tarball that can be unpacked somewhere and just works as long as the external dependency requirements are met.  I'll start working on this cleanup right after the current release, and the git clone lines of your proposed installation script will become a simple tarball extraction.  However, we'll still need scripts that installs runtime dependencies for each platform and backend database pair, so we should put more attention to this end.  It would be nice if we can nail down the layout for the scripts in this release and eventually eliminate all variants we have.  If you don't mind, I'll fork your branch to have our Makefile and travis rely on it.

**Comment by raphaelhoffmann** [comment]
Sounds great. I agree that the testing frameworks can also be based on the same scripts. For my use cases, I'm actually fine with building the sources from scratch for every install. Our code base (develop) is changing so frequently that a pre-built image often won't work for me. I think it would be great to make the script better to show helpful error messages, allow fully automated mode, check all dependencies, support OSX, etc.
