### ISSUE TITLE
DeepDive v0.7.0 is backward incompatible

### ISSUE THREAD

**Issue by zifeishan** [HazyResearch/deepdive#346]
@netj  Now one cannot run "deepdive -c application.conf -o output_dir".

For an application with previous versions, what should a user do to make the application compatible? One might have different configuration files for an application.

**Comment by netj** [comment]
You're right.  v0.7.0 introduced big changes, but that's why the version number was bumped.  It is strongly recommended to reorganize your code according to [the new standard app layout](http://deepdive.stanford.edu/doc/advanced/deepdiveapp.html) to use the latest version because a lot of other features will assume it.

However, for the moment, I believe you can rewrite the command as follows, similar to how [an example that's not fully migrated yet](https://github.com/HazyResearch/deepdive/blob/48b4b79b0ba2933ad7e38641df92e0d35d4a929a/examples/spouse_example/postgres/incremental/run.sh#L40) is doing:
```bash
deepdive env java org.deepdive.Main -c application.conf -o output_dir
```

The `deepdive run` command in fact supports the `-c` and `-o` options, although they aren't well documented yet.
