### ISSUE TITLE
Separate initdb command / flag for input data vs. extractions schemas

### ISSUE THREAD

**Issue by ajratner** [HazyResearch/deepdive#351]
This is minor / low-priority, but it's convenient to be able to e.g. add a new entity type or otherwise tweak the schema, and then run something like initdb, without also dropping the sentences table say...

**Comment by chrismre** [comment]
This should have been fixed a long time ago... @netj @feiranwang ... :)
Let's get it done!!!

**Comment by netj** [comment]
Sounds like a great suggestion!  Admittedly, the current initdb command that literally initializes the whole database is not very friendly to such incremental changes.  It was the best abstraction at the moment given the opaque schema.sql and setup_database.sh-style scripts most apps were using.  Ideally, I think DeepDive should have more visibility into the database schema to provide finer grained control.

Speaking more concretely:
* [ ] We could replace schema.sql with a schema.json where the backend-specific CREATE TABLE SQLs are generated by DD.  This JSON format could stay in sync with DDlog's, which becomes another reason to use DDlog!

  Example [schema.json](https://github.com/HazyResearch/ddlog/blob/master/test/expected-output-test/annotations/export-schema.expected).

* [ ] Creating/truncating database tables individually could be done much easily, e.g.:
    ```bash
    deepdive initdb sentences ontology mentions
    ```

* [ ] Instead of having the flat and opaque `input/init.sh` script do everything, we could set up a granular convention for keeping the data/script to load into individual tables, e.g.:
    ```bash
    deepdive load sentences
    ```
  loading `input/sentences.{tsv,csv,json-seq}` or running `input/load-sentences.sh`.  It'd be great to have this directly load columns produced by [Bazaar Pipe](https://github.com/HazyResearch/bazaar/tree/master/pipe) as well.

* [ ] Detecting changes to the schema becomes also significantly easier, and we could provide a handy way to evolve the schema, e.g., running autogenerated ALTER TABLEs with something like:
    ```bash
    deepdive migrate gene_mentions
    ```


@chrismre I think there may have been a similar sounding issue in the past, but I believe this is a new thing due to the deepdive command we introduced in the latest release.

**Comment by ajratner** [comment]
These ideas are all awesome!

In our `dd-genomics` repo (still pre-`0.7.0`) we just split our `create_schema.sh` utility script into two-
* one for the "input" fields (e.g. the `sentences` table, anything else that might have been the result of expensive pre-processing)
* one for everything else (stuff that would be re-computed each full run of dd anyway)

This has been good enough for us for the most part.  But fine grained control such as the above would obviously be even better

In particular I really like your first point/idea.  The schema file seems so absolutely central to a deepdive app that it really would be great to have it specified in a single file only (and even better, a json file :) )

**Comment by chrismre** [comment]
Any updates? This is an obvious pain point in the language that we should take care of soon! :)

**Comment by feiranwang** [comment]
`deepdive load` is added in #368. I'll also take care of making `initdb` to be able to create specific tables.
