### ISSUE TITLE
schema.sql file generated from ddlog?

### ISSUE THREAD

**Issue by ajratner** [HazyResearch/deepdive#357]
Is this on the roadmap out of curiosity?  Seems like this would be nice and also fairly simple way to centralize the basic DD app in the ddlog file- or is there a way to do this already?  Thanks!

**Comment by chrismre** [comment]
I like it!

**Comment by alldefector** [comment]
Do we plan to keep the ddlog --> conf --> DD flow in the long term? The translation loses the nicely defined user schema in ddlog even if it does generate the .sql file.

@netj any plan to pass all the structures (schema, rules) in ddlog to DD directly so that DD can more tightly manage the database (e.g., creating / loading / altering user tables directly instead of having the cumbersome .sql file)?

**Comment by netj** [comment]
@alldefector Yes, that's certainly where we're headed.  We're trying to preserve DDlog's high-level info in a JSON format to do various operations.  @feiranwang has already made some progress on the creating/altering parts in #376 and we'll try to expose more operations to give complete control to the user.
