### ISSUE TITLE
Failed installation for deepdive runtime deps:Can not run:sudo apt-get update

### ISSUE THREAD

**Issue by astrung** [HazyResearch/deepdive#362]
When i installed deepdive runtime deps,and run this command:sudo apt-get update,i get this error:
"E: Some index files failed to download. They have been ignored, or old ones used instead.",
"W: Failed to fetch http://ubuntu.uhost.hk/dists/trusty-updates/main/i18n/Translation-en  Hash Sum mismatch".
But if i run that update command directly from system,everything is fine.
This error is occured when it uses update command from this command:
bash <(curl -fsSL deepdive.stanford.edu/install) _deepdive_runtime_deps.
Can someone explain for me?

**Comment by chrismre** [comment]
@feiranwang @netj @zhangce I thought we had this all nicely fixed on ubuntu? :)

**Comment by netj** [comment]
@astrung Sorry you ran into this.  Could you tell us whether that failing update is happening after some `debconf` and `add-apt-repository` commands?  (Creating a [gist](http://gist.github.com) of your entire output may be much more helpful.)  Have you tried changing your Ubuntu mirror to a more reliable one?  It seems [the one you're using](https://launchpad.net/ubuntu/+mirror/ubuntu.uhost.hk-archive) is not up-to-date.  I'm not sure how apt-get update could only fail from our installer script because we're not altering anything specially.

@chrismre This runtime dependency installer is actually being tested on Travis upon every build.  However as you know, some unusual user configuration can always break things.  We could take a more aggressive approach to bundle exact versions of all our dependencies to make these errors much less probable.

**Comment by astrung** [comment]
After i change your Ubuntu mirror,it is fine.Thank you.
But it is neccessary to update system when install Deepdive??

**Comment by netj** [comment]
@astrung Glad to hear it worked.  The installer makes sure you have all the dependencies installed upfront to save you from debugging runtime errors.  You can install just DeepDive without any system updates using the `deepdive_from_release` option.
