### ISSUE TITLE
Collect examples for the relation without Distant supervision

### ISSUE THREAD

**Issue by astrung** [HazyResearch/deepdive#371]
Now i want to extract some relations,but i can not find that relations from any databases.So we can write applications without training data for relations(without Distant supervision)?

**Comment by chrismre** [comment]
Absolutely! This may require some conversation about how to do it properly... but in our human trafficking applications there are essentially no databases and distant supervision works well...

one way to think about it is to write some (low quality) simple rules as distant supervision. for example, we had lots of collisions about which location (is it concord CA? TX?) -- but we heuristically used phone number to grab those which were less ambiguous. 

Since I don't know the domain, I can't generate these rules... but this would be fun to meet about...

@ajratner @netj would love to have that elastic search regular expression integration... then as they search for rules we could _data program_ :)

**Comment by astrung** [comment]
If we don`t have any positive and negative examples,how to learn the weight of a factor???we can generate a constant or depend on some variables for it,but if we have some negative candidates for a relation,i am not sure that deepdive can give small weights automatically for them without examples

**Comment by chrismre** [comment]
Roughly, the game works like this:

* You heuristically generate many different kinds of low quality examples. Concretely, you write a bunch of regular expressions and python code. They labels you generate will be noisy--this is OK. It's a little disturbing from a classical ML perspective but fine from a stat/optimization perspective. 

* Now, the game is to get some redundancy in the labels so that you can "denoise the labels" Also, if there is structure between the label sets, you can even denoise to an even greater extent. 

* Of course, you may choose to label some data or to fix some rules, but engineering-wise it's hopefully easier... we have some theory that gives situations in which noise from many crappy rules is enough to learn to essentially perfect accuracy. 

But, it's mostly in latex, and we need more experience... hence my excitement :) 

We're building tools to support this type of extreme distant supervision... @zhangce @ajratner @netj @thodrek  COULD BE FUN!!

**Comment by astrung** [comment]
@chrismre When do you complete your tools?:))

**Comment by chrismre** [comment]
I don't know... :) @netj

**Comment by alldefector** [comment]
@astrung the "data programming" process that @chrismre is not embodied in https://github.com/HazyResearch/snorkel
