### ISSUE TITLE
Increase performance for deepdive app

### ISSUE THREAD

**Issue by astrung** [HazyResearch/deepdive#399]
My deepdive app run slowly with some big datasets,and i want to ask some tips to improve performance:
-When we read data from databases,if we have so many,many rows in that table,Deepdive apps will read all records from databases,then execute Python scripts for all of its or read one records to execute Python scripts???if we can not read all records in memory,we have any other options???
-If we add small datasets to deepdive app,and we want run deepdive app for only that datasets(not  from all datasets what i have in deepdive app) with inference rules and factor graphs what i had built ,how to do it??

**Comment by netj** [comment]
Hi @astrung,

- The first one isn't an issue because DeepDive streams the records from database to the Python UDFs, and as long as the UDF operates on each row independently (row-wise extractor), memory won't be a limit.  There is however an implementation artifact that duplicates the input data for UDF on filesystem (#428), so the disk storage can be a limit.   But we plan to lift this limitation soon by not spilling to disk.

- I think you're asking for the [`pipeline.relearn_from` configuration](http://deepdive.stanford.edu/doc/basics/configuration.html#pipelines) which allows you to test with what's already learned.
