### ISSUE TITLE
Open data in a better format than .zip?

### ISSUE THREAD

**Issue by netj** [HazyResearch/deepdive#407]
.zip files need to be fully downloaded for any of its files to be extracted, which renders any partial download useless.
If the datasets were published in .tar.gz with smaller files (e.g., README) at the beginning, then it's possible to extract whatever files that exist in the first part of the archive.

**Comment by zhangce** [comment]
@netj is this really necessary? The goal of the teaser data set is to make sure the user can download a small sample instead of the whole file... Can you let me know more details why the teaser data set is not enough such that the user need to download partial full data set with this trick?

If there is a need to download partial dataset larger than the teaser but smaller than the full, I can add a larger teaser in the middle.

**Comment by netj** [comment]
I partly agree this isn't crucial with the teaser.  In my case, I was trying to confirm the whole dataset's format was identical to the teaser, but it was too large to download.  I thought we could switch to a superior format because we're going to republish them anyway for fixing other bugs.

**Comment by zhangce** [comment]
>> because we're going to republish them anyway for fixing other bugs.

Only 2 out of 8 datasets need republishing. I will make the new ones
.tar.gz. (I personally like zip better but that's not important :)) For the
others, I will leave them untouched for now if it does not impact user
experience.

Ce
