### ISSUE TITLE
mkmimo/deepdive-compute issues

### ISSUE THREAD

**Issue by raphaelhoffmann** [HazyResearch/deepdive#480]
Still having a problem with mkmimo/deepdive-compute. 

Checked out docathon-v0.8 and am trying to run a program similar to the chunking example in ddlog (Ubuntu/Postgres).  Whenever deepdive-compute is called, execution is taking a very long time, or stalls. Running the commands manually, however, is working fine:
```
deepdive sql 'COPY (SELECT "weights"."id" AS "weight_id" , "factors"."tag.R0.id" FROM "dd_query_inf_istrue_tag" "factors", "dd_weights_inf_istrue_tag" "weights" WHERE "factors"."dd_weight_column_0" = "weights"."dd_weight_column_0") TO STDOUT' | tee >(wc -l >nfactors.part-1) | format_converter factor /dev/stdin >(pbzip2 >factors.part-1.bin.bz2) 5 1 original 1 | tee nedges.part-1
```
I tried adjusting `THROTTLE_SLEEP_MSEC` and `DEEPDIVE_NUM_PROCESSES`. Is there another setting I should be looking at?

In another experiment, I tried running the spouse_example using master branch on OSX, but my laptop freezes after running mkmimo for a while.

**Comment by netj** [comment]
@raphaelhoffmann You mean feeding the deepdive-sql's  output directly to the `format_converter`/`wc` processes works fine but hangs with the run/process/**/dump/run.sh?  I couldn't easily reproduce the slow progress.

There apparently is an mkmimo issue on Mac.  Non-blocking mkmimo seems to create sudden high load to the CPU, then reboots every Mac, probably because of heat/temperature surge?  I'm investigating how to fix this, but I'm hoping a multithreaded implementation with blocking I/O could mitigate this.  For the moment I recommend keeping the `DEEPDIVE_NUM_PROCESSES` low like 3-4.

**Comment by alldefector** [comment]
@raphaelhoffmann mentioned that he saw this problem on Linux as well...

**Comment by raphaelhoffmann** [comment]
@netj Thanks for looking at this. I'm on commit 802ec0d5284704c1b8bdd71c8a788758553d19ef and am trying to run the chunking example. Let me send you the logs.

**Comment by netj** [comment]
@alldefector mkmimo crashing Linux? I haven't experienced that myself yet. The potentially low throughput may also be due to a database issue.

**Comment by raphaelhoffmann** [comment]
@netf found the problem: there are some conditions missing in a query in the example, see here https://github.com/HazyResearch/deepdive/blob/docathon-v0.8/examples/chunking/app.ddlog#L38 
I added `[word_id1 = word_id2 + 1], word1 != NULL`, but am still investigating why results are not the same as with old chunking example.

**Comment by raphaelhoffmann** [comment]
Problem is now fixed with https://github.com/HazyResearch/deepdive/pull/485
