### ISSUE TITLE
Grounding complexity: Fingerprinting to the rescue?

### ISSUE THREAD

**Issue by alldefector** [HazyResearch/deepdive#539]
The grounding step is getting out of hand especially as we try to support dynamic scope multinomials properly. It's already a beast of complicated translations between the string space and the array space for variables, factors, and weights. And now we need to add the extra dimension of (multinomial) variable values to the mix (it's been added, but not properly).

Such translation so far has entailed slow "ID assignment" steps, big inefficient grounding SQL, and hard-to-maintain code in the compiler and sampler.

I'm not familiar with the sampler enough to know how critical the array representations of the factor graph are for performance (e.g., CPU cache optimization). But if it's ok to not use sequential IDs (and hence arrays) but rather hash tables (e.g., unordered_map), we could replace the slow ID assignment and complicated SQL joins with a fingerprinting function. That would probably greatly simplify both the compiler and the sampler, speed things up, and make it easy to introduce features like dynamic scope multinomials. @zhangce @netj

**Comment by chrismre** [comment]
This really shouldn't be so hard to resolve. Introducing a probe on each variable and factor could be a killer for performance... However, since after an initial pass the indexes are completely resolved, one could imagine bloating the data structure slightly to cache the needed indexes/pointers.

What makes me a little concerned is that...I'm not sure why this code is difficult or complex... it's a relatively straightforward bit of code. It's not clear to me that this change isn't to fix a symptom of the deeper problem of low quality code in the compiler.

**Comment by netj** [comment]
@alldefector I share the same high-level concerns about complexity with you, but the rest of your arguments don't seemed to be factual or convincing to me.

1. First, the consecutive id assignment step itself isn't a major bottleneck.  Joining the assigned ids back is clearly an overhead, but it's what we pay for higher performance later.  Moreover, using a different method that computes unique ids for variables and weights may not necessarily be cheaper as @chrismre mentioned.

2. Consecutive sequential id is crucial for the sampler to keep its sequential access pattern.  Otherwise, the sampler itself will eventually have to do similar graph rewriting from each fingerprint to a compact space at loading time. (unordered_map can't be used literally in the code.)  Without the id assignment, grounding is just deferring the problem to a later component, not solving the impedance mismatch at the right place and moment.

3. The user-space to array-space mapping is the core of DeepDive's grounding.  You can't take that out and let user be responsible for it.  If users already have matrices and arrays, nicely mapped from their raw data, why bother using DeepDive and not Julia or a ton of other packages?  I see DD's core value as helping users construct such array-space objects for analytics without having to deal with the underlying data management plumbing.

Regarding complexity (also to @chrismre): I don't think the current implementation is complicated at all; It's just linear to the complexity it has to handle.  For every V, F, W, D (scopes for categoricals) to be grounded, the compiler has a SQL template and a few pipeline before/after to map user's spec to a SQL query.  Then to deal with the difference Boolean vs. categorical/multinomial introduces to each of those, doubling the SQL templates from four to eight.  Of course there are hidden/intermediate data for the real work of id assignment, each of which also has a SQL template, making up to about 10 SQL templates.  So, if you think keeping all of these ~10 SQL templates in [a single file](https://github.com/HazyResearch/deepdive/blob/c303c9c7ac9d130ba60dcaab52e74c0d1937ebe4/compiler/compile-config/compile-config-2.01-grounding) is really what makes it difficult to reason about, we can easily split into smaller pieces by literally cut/pasting them into separate files.  Grounding was just put in one blob initially while others were sliced and diced as I wasn't sure what separation-of-concerns would be ideal for the future.  It seems we can at least separate it into three now: the Boolean/multinomial cases and the common steps for both.  (@zifeishan may be able to help make this happen sooner)

One interesting direction to explore is turning the id assignment (hence grounding) into two phases: first use fingerprint to deal with user-space to fingerprint mapping; then have the second phase deal with fingerprint to sequential id mapping--which sounds nearly identical to the current grounding but hopefully simpler as we can contain complexity in user's data/code in the first phase (many vars, factors, etc.).  The second phase may become simpler and easier to understand as it focus on the core problem: taking a simplified table from the first phase, mapping fingerprints in V, W to a sequential ids, then rewriting fingerprints in F to sequential ids with the maps while generating input for the sampler.

**Comment by alldefector** [comment]
Sorry for being curt in the first post... Since the variable and factor arrays are critical for the sampler's performance, we have to do the ID sequentialization at some point. I like the two-phase idea, and think that it can probably indeed simplify things: the fingerprinting would simplify the SQL joins (no more ID mapping tables shadowing every base table), and the second-phase mapping might actually be easily doable by the sampler's loading phase (by keeping a few fingerprint->ID lookup tables in memory).

**Comment by alldefector** [comment]
Tabling this for now that I've become the 2nd person who can work with the jq code...
