### ISSUE TITLE
slash escape in `deepdive sql eval`

### ISSUE THREAD

**Issue by xiaoling** [HazyResearch/deepdive#552]
```
deepdive sql "create table tmp(t text)"
deepdive sql "insert into tmp values ('\\\\u00a0')"
```

In the db, the query will print out `\u00a0`
```
db=# select * from tmp;
   t
--------
 \u00a0
(1 row)
```

If I run `deepdive sql eval 'select * from tmp'`, it will print out `\\u00a0`
```
$ deepdive sql eval 'select * from tmp'
\\u00a0
```

Is this desired? @netj

**Comment by alldefector** [comment]
We use TSV very extensively. I have seen folks patching the symptoms of issues like this in many places. This is a fundamental issue for data in motion (and at rest) in general. We need to nail down a robust data format and stick with it consistently everywhere. Just "TSV" is not specific enough as a standard.

**Comment by netj** [comment]
It's escaped as per [Postgres' TSV or TEXT format](https://www.postgresql.org/docs/9.5/static/sql-copy.html#AEN74386).

Your `insert into` gives me a different result, but it seems you're inserting a literal backslash, and that's what you're seeing from the psql prompt.

I get the same if I do this:
```bash
$ deepdive sql 'insert into tmp values ('\''\u00a0'\'')'
INSERT 0 1
$ deepdive sql eval 'select * from tmp'  
\\u00a0
```
However, if you use CSV, you get the literal text:
```
$ deepdive sql eval 'select * from tmp' format=csv
\u00a0
```
So, it's clearly literal backslash that's inserted by the SQL.

Note that this is completely different if you use the `E'...'` in Postgres' SQL.
```bash
$ deepdive sql 'insert into tmp values (E'\''\u00a0'\'')'
INSERT 0 1
$ deepdive sql eval 'select * from tmp'  
 
$ deepdive sql eval 'select * from tmp'  format=csv
 
$ deepdive sql eval 'select * from tmp'  format=json
{"t":" "}
```

**Comment by alldefector** [comment]
So looks like PG COPY by default escapes chars with backslash, and `deepdive sql` internally wraps the query with COPY. When the original string has a single backslash, a user probably won't expect the output of `deepdive sql` to contain two backslashes.
1. Maybe we want to override the default escaping behavior of COPY with things like `ESCAPE WITH E'\b'` so that what the user sees with `psql` is also what she gets with `deepdive sql`?
2. We may also want to change other DeepDive operators (e.g., load) similarly to be symmetric.
3. The SerDe behavior needs to be well-known to users so that other systems know how to consume / produce data.

**Comment by netj** [comment]
`deepdive sql` so far did not define its own format and simply tried to stick with standard PG TSV, CSV, or JSON-object-per-line formats.  I don't think `deepdive sql` introduces any surprise when the user gets an escaped backslash for a backslash they INSERTed in this case.  Doing otherwise would be a huge surprise corrupting user's data.  It's rather the careless user's fault or PG's confusing SQL literal syntax to be blamed rather than the `deepdive sql` trying to stay consistent per standard PG TSV encoding.  If it were input TSV that contained a single backslash, there of course won't be extra backslash escapes, but the record was inserted via SQL in this case.

I agree we need a very clear and simple SerDe.  Our assumption was that PG's TSV was simple but actually it's much worse than what it appears to be at the surface.  The complexity of TSV places a huge burden on everyone who consumes/produces it.  It cannot be solved by a single entity.  Every UDF or tool that wants to produce a correct TSV has to deal with all of its corner cases, which is hard and confusing, hence the current chaos.  I think we should consider completely ditching the PG TSV format and moving to a saner one that can be solved once by the infra eliminating the burden on every consumer/producer.

I came to a conclusion that JSON is the simplest encoding that's universally available.  However, repeating the data schema by encoding each row as a JSON object is too wasteful and suboptimal.  Hence, I think we should use something like *TSJ (tab-separated JSON)* I've been prototyping which doesn't repeat the schema (or column names) but still keeps each column in JSON encoding to eliminate any burden of correct SerDe implementation.  That way we can guarantee the data in motion and rest can be read and written without any issues.  TSJ in particular simply requires the consumer to 1) split by TAB, then 2) parse each column in JSON, and the producer to 3) encode each column in JSON then 4) join by TAB to emit a line.  I'm pretty sure TSJ is the simplest one can get that can be programmed in 1-2 lines in most programming languages.  PG TSV requires at least a hundred lines of Python code, and we can never be sure if it's correct or not.  This has to be repeated for every programming language we may need to use for consuming the data.

**Comment by alldefector** [comment]
As far as universal support goes, JSON encoding does seem to be the best choice and TSJ seems like a great tradeoff between simplicity, usability, and performance. I think we can probably commit to TSJ as the standard human-readable data format if we can do it without adding much overhead in terms of both human efficiency and machine efficiency.

Specifically, we need to decide where and how to plug in the SerDe implementation. For example, if it's only in DeepDive, people won't be able to load and unload data in desired format by directly interacting with the DB. So either we let DeepDive monopolize data load/unload, or we need to implement/distribute the SerDe inside the DB server or alongside DB clients (namely wherever people call psql). Or maybe we can just make it clear that ad hoc load/unload is outside the TSJ sphere and extra care is required for ad hoc data to join the sphere.

Another concern is speed. For example, can we make TSJ loading at most 10% slower than TSV loading? Would `json.loads` calls in Python slow down a dummy UDF's throughput by 10X?

JSON string quoting seems simple enough: http://stackoverflow.com/a/27516892
Given that, would we like to roll our own specialized faster parser/serializer in case the standard JSON routines are slow?

**Comment by xiaoling** [comment]
> Your insert into gives me a different result, but it seems you're inserting a literal backslash, and that's what you're seeing from the psql prompt.

Sorry for the confusion. My intention was to insert a literal backslash. In the original example, the field is for a json string where the unicode char is stored literally. I guess `PG COPY` is escaping the field that we don't need it to.

> However, if you use CSV, you get the literal text:

Thanks for the tip. But the problem is that this issue came up when the table is printed out as the input to a udf. I'm not sure if we can specify the csv format inside DeepDive & ddlog. Maybe in this case, I should do something like (borrowing the spouse app for example)?

```
function nlp_markup over (
        doc_id  text,
        content text
    ) returns rows like sentences
    implementation "udf/nlp_markup.sh" handles *csv/json* lines.
```

Is this supported?

**Comment by netj** [comment]
> Sorry for the confusion. My intention was to insert a literal backslash. In the original example, the field is for a json string where the unicode char is stored literally. I guess `PG COPY` is escaping the field that we don't need it to.

`PG COPY` has to escape backslashes for consistency because it'll escape any newline in the field with `\n` for example.  Without it, you're getting corrupted data, even though such whitespace may not influence parsed JSON, it matters for other fields.

> Thanks for the tip. But the problem is that this issue came up when the table is printed out as the input to a udf. I'm not sure if we can specify the csv format inside DeepDive & ddlog. Maybe in this case, I should do something like (borrowing the spouse app for example)?
> ... `handles *csv/json* lines.`
> Is this supported?

Nope.  CSV is very awkward for parallelizing as you need to fully parse it just to find the record boundaries, so it's not supported and won't be.  The only option at the moment is having the UDF to fully handle all the PG TSV escape sequences, which is actually nontrivial and why we want a simpler data exchange format for everyone.  If it's a Python UDF, we fortunately have solved the problem in ddlib.util as a `@tsv_extractor` decorator.  However, for other environment, I'm sorry but you're on your own.

Is this a problem hooking up Bazaar/Parser?

**Comment by netj** [comment]
@alldefector Sorry for the lag.  I thought I posted a long answer the other day, but lost it somewhere.

SerDe for semi-structured data in PG TSV is hard and JSON within TSV simply propagates the extra overhead for TSV escaping/unescaping everywhere, so yes, something like TSJ is desirable as the standard data exchange format.  The culprit is the awkwardness of PG COPY formats.  Everyone else can be happy once we put a thin wrapper around it for data load/unload and that's what's going to done by DeepDive.  TSJ can remain very simple in PG's relational schema as well: nothing special for primitive types, JSON encoding for any structured data instead of PG's ARRAY or so.  Therefore, we don't need DeepDive to monopolize data load/unload although it should be strongly recommended over a direct psql COPY FROM serialized data.  For any direct access, e.g., JDBC, psycopg, nothing special.

On your concern about speed: I'd say parsing JSON can't be slower than a real PG TSV parser for the equivalent data.  It surely will be slower than a crappy UDF that ignores all PG TSV escape sequences, corrupts data and crashes itself.  However a decent JSON library in any given language (often optimized by hand or native code) isn't going to be slower than a crude implementation of full PG TSV.  DeepDive's db-driver will try not to parse the full JSON but just work with TSV escapes to keep the overhead minimal (see: [tsv2tsj](https://github.com/HazyResearch/deepdive/blob/abc5de2a9c5499cde2a86a751323ebd936a4d0b9/database/tsv2tsj#L32-L41) and [tsj2fmt](https://github.com/HazyResearch/deepdive/blob/abc5de2a9c5499cde2a86a751323ebd936a4d0b9/database/tsj2fmt)).

**Comment by netj** [comment]
Nothing to be done in DD for this.

Take away: PG TSV encoding is misleading and difficult; let's move to something else, probably TSJ.
